import { ArrowUpCircleIcon, ArrowUpIcon } from "@heroicons/react/24/solid"
import About from "components/About"
import ContactMe from "components/ContactMe"
import Header from "components/Header"
import Hero from "components/Hero"
import Projects from "components/Projects"
import Skills from "components/Skills"
import WorkExperience from "components/WorkExperience"
import Head from "next/head"
import Link from "next/link"

export default function Home() {
	return (
		<div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 scrollbar scrollbar-thumb-[#F7AB0A]/80 scrollbar-track-gray-400/20 scroll-smooth transition duration-150">
			<Head>
				<title>Ayoub's Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<Header />
			<section
				id="hero"
				className="snap-start"
			>
				<Hero />
			</section>

			<section
				id="about"
				className="snap-center"
			>
				<About />
			</section>

			<section
				id="experience"
				className="snap-center"
			>
				<WorkExperience />
			</section>

			<section
				id="skills"
				className="snap-center"
			>
				<Skills />
			</section>

			<section
				id="projects"
				className="snap-center"
			>
				<Projects />
			</section>

			<section
				id="contact"
				className="snap-center"
			>
				<ContactMe />
			</section>
			<footer className="sticky bottom-0 z-50 flex items-center justify-center py-5">
				<Link
					href="#hero"
					className="bg-[#cc8e08] hover:bg-blue-500 rounded-full transition duration-300"
				>
					<ArrowUpIcon className="h-[50px] w-[50px] rounded-full text-black hover:text-white p-[10px] transition duration-300" />
				</Link>
			</footer>
		</div>
	)
}
